# This justfile compiles the code and copies the executable in the current
# working directory. After modifying the source code, remember to recompile the
# code and commit the changes to the executable.

export RUSTFLAGS := "-C llvm-args=--sbf-expand-memcpy-in-order -C llvm-args=--combiner-store-merging=false -C llvm-args=--combiner-load-merging=false -C llvm-args=--aggressive-instcombine-max-scan-instrs=0 -C llvm-args=--combiner-reduce-load-op-store-width=false -C llvm-args=--combiner-shrink-load-replace-store-with-store=false -C strip=none -C debuginfo=2"
export EXECUTABLE_PATH := "./target/sbf-solana-solana/release/calltrace_range_info_tests.so"

build-sbf:
    echo "env RUSTFLAGS=$RUSTFLAGS"
    cargo +solana build-sbf
    cp $EXECUTABLE_PATH .
